COMMENT ON COLUMN dim_exoplanet.target_name IS 'Standard IAU name of target (from a list related to target class), case sensitive';
COMMENT ON COLUMN dim_exoplanet.target_class IS 'Type of target, from a controlled vocabulary.';
COMMENT ON COLUMN dim_exoplanet.spatial_frame_type IS 'Flavor of coordinate system, defines the nature of coordinates. From a controlled vocabulary, where "none" means undefined.';
COMMENT ON COLUMN dim_exoplanet.instrument_host_name IS 'Standard name of the observatory or spacecraft';
COMMENT ON COLUMN dim_exoplanet.instrument_name IS 'Standard name of instrument';
COMMENT ON COLUMN dim_exoplanet.measurement_type IS 'UCD(s) defining the data, with multiple entries separated by hash (#) characters.';
COMMENT ON COLUMN dim_exoplanet.processing_level IS 'Dataset-related encoding, or simplified CODMAC calibration level [Note et_cal]';
COMMENT ON COLUMN dim_exoplanet.creation_date IS 'Date of first entry of this granule';
COMMENT ON COLUMN dim_exoplanet.modification_date IS 'Date of last modification (used to handle mirroring)';
COMMENT ON COLUMN dim_exoplanet.release_date IS 'Start of public access period';
COMMENT ON COLUMN dim_exoplanet.service_title IS 'Title of resource (an acronym really, will be used to handle multiservice results)';
COMMENT ON COLUMN dim_exoplanet.publisher IS 'A short string identifying the entity running the data service used';
COMMENT ON COLUMN dim_exoplanet.bib_reference IS 'Bibcode or DOI preferred if available, or other bibliographic identifier or URL';
COMMENT ON COLUMN dim_exoplanet.target_region IS 'Region of interest';
COMMENT ON COLUMN dim_exoplanet.species IS 'Species detected in the planet';
COMMENT ON COLUMN dim_exoplanet.detection_type IS 'Methods of discovery/detection of the planet (RV, transit, TTV, lensing, astrometry, imaging). The first method is the discovery one';
COMMENT ON COLUMN dim_exoplanet.publication_status IS 'Publication status of exoplanet information';
COMMENT ON COLUMN dim_exoplanet.discovered IS 'Year of discovery at the time of acceptance of a paper';
COMMENT ON COLUMN dim_exoplanet.remarks IS 'remarks';
COMMENT ON COLUMN dim_exoplanet.other_web IS 'other web';
COMMENT ON COLUMN dim_exoplanet.mass_detection_type IS 'Method of measurement of the planet mass (RV, astrometry, planet model for direct imaging)';
COMMENT ON COLUMN dim_exoplanet.radius_detection_type IS 'Method of measurement of the planet radius (transit, planet model for direct imaging)';
COMMENT ON COLUMN dim_exoplanet.alt_target_name IS 'Alternatives names of the planet';
COMMENT ON COLUMN dim_exoplanet.star_name IS 'Name of the host star';
COMMENT ON COLUMN dim_exoplanet.external_link IS 'Url of the planet page on exoplanet.eu';
