COMMENT ON COLUMN fact_observation.time_min IS 'Acquisition start time (in JD), as UTC at time_refposition';
COMMENT ON COLUMN fact_observation.time_max IS 'Acquisition stop time (in JD), as UTC at time_refposition';
COMMENT ON COLUMN fact_observation.time_sampling_step_min IS 'Sampling time for measurements of dynamical phenomena, lower limit.';
COMMENT ON COLUMN fact_observation.time_sampling_step_max IS 'Sampling time for measurements of dynamical phenomena, upper limit';
COMMENT ON COLUMN fact_observation.time_exp_min IS 'Integration time of the measurement, lower limit.';
COMMENT ON COLUMN fact_observation.time_exp_max IS 'Integration time of the measurement, upper limit';
COMMENT ON COLUMN fact_observation.spectral_range_min IS 'Spectral range (frequency), lower limit.';
COMMENT ON COLUMN fact_observation.spectral_range_max IS 'Spectral range (frequency), upper limit';
COMMENT ON COLUMN fact_observation.spectral_sampling_step_min IS 'Spectral sampling step, lower limit.';
COMMENT ON COLUMN fact_observation.spectral_sampling_step_max IS 'Spectral sampling step, upper limit';
COMMENT ON COLUMN fact_observation.spectral_resolution_min IS 'Spectral resolution, lower limit.';
COMMENT ON COLUMN fact_observation.spectral_resolution_max IS 'Spectral resolution, upper limit';
COMMENT ON COLUMN fact_observation.c1min IS 'Right Ascension (ICRS), lower limit.';
COMMENT ON COLUMN fact_observation.c1max IS 'Right Ascension (ICRS), upper limit';
COMMENT ON COLUMN fact_observation.c2min IS 'Declination (ICRS), lower limit.';
COMMENT ON COLUMN fact_observation.c2max IS 'Declination (ICRS), upper limit';
COMMENT ON COLUMN fact_observation.c3min IS 'Distance from coordinate origin, lower limit.';
COMMENT ON COLUMN fact_observation.c3max IS 'Distance from coordinate origin, upper limit';
COMMENT ON COLUMN fact_observation.s_region IS 'ObsCore-like footprint, valid for celestial, spherical, or body-fixed frames';
COMMENT ON COLUMN fact_observation.c1_resol_min IS 'Resolution in the first coordinate, lower limit.';
COMMENT ON COLUMN fact_observation.c1_resol_max IS 'Resolution in the first coordinate, upper limit';
COMMENT ON COLUMN fact_observation.c2_resol_min IS 'Resolution in the second coordinate, lower limit.';
COMMENT ON COLUMN fact_observation.c2_resol_max IS 'Resolution in the second coordinate, upper limit';
COMMENT ON COLUMN fact_observation.c3_resol_min IS 'Resolution in the third coordinate, lower limit.';
COMMENT ON COLUMN fact_observation.c3_resol_max IS 'Resolution in the third coordinate, upper limit';
COMMENT ON COLUMN fact_observation.incidence_min IS 'Incidence angle (solar zenithal angle) during data acquisition, lower limit.';
COMMENT ON COLUMN fact_observation.incidence_max IS 'Incidence angle (solar zenithal angle) during data acquisition, upper limit';
COMMENT ON COLUMN fact_observation.emergence_min IS 'Emergence angle during data acquisition, lower limit.';
COMMENT ON COLUMN fact_observation.emergence_max IS 'Emergence angle during data acquisition, upper limit';
COMMENT ON COLUMN fact_observation.phase_min IS 'Phase angle during data acquisition, lower limit.';
COMMENT ON COLUMN fact_observation.phase_max IS 'Phase angle during data acquisition, upper limit';
COMMENT ON COLUMN fact_observation.time_scale IS 'Defaults to UTC in data services; takes values from http://www.ivoa.net/rdf/time_scale otherwise';
COMMENT ON COLUMN fact_observation.mass IS 'Mass of the planet';
COMMENT ON COLUMN fact_observation.mass_error_min IS 'Mass error min';
COMMENT ON COLUMN fact_observation.mass_error_max IS 'Mass error max';
COMMENT ON COLUMN fact_observation.radius IS 'Radius of the planet';
COMMENT ON COLUMN fact_observation.radius_error_min IS 'Radius error min';
COMMENT ON COLUMN fact_observation.radius_error_max IS 'Radius error max';
COMMENT ON COLUMN fact_observation.semi_major_axis IS 'Semi-major axis of the planet orbit';
COMMENT ON COLUMN fact_observation.semi_major_axis_error_min IS 'Semi-major axis error min';
COMMENT ON COLUMN fact_observation.semi_major_axis_error_max IS 'Semi-major axis error max';
COMMENT ON COLUMN fact_observation.period IS 'Orbital period of the planet';
COMMENT ON COLUMN fact_observation.period_error_min IS 'Orbital period error min';
COMMENT ON COLUMN fact_observation.period_error_max IS 'Orbital period error max';
COMMENT ON COLUMN fact_observation.eccentricity IS 'Eccentrity of the planet orbit from 0, circular orbit, to almost 1, very elongated orbit';
COMMENT ON COLUMN fact_observation.eccentricity_error_min IS 'Eccentrity error min';
COMMENT ON COLUMN fact_observation.eccentricity_error_max IS 'Eccentrity error max';
COMMENT ON COLUMN fact_observation.periastron IS 'Periapse longitude : angle between the periapse and the line nodes in the orbit plane';
COMMENT ON COLUMN fact_observation.periastron_error_min IS 'Periapse error min';
COMMENT ON COLUMN fact_observation.periastron_error_max IS 'Periapse error max';
COMMENT ON COLUMN fact_observation.tzero_tr IS 'Time of passage at the center of the transit light curve for the primary transit';
COMMENT ON COLUMN fact_observation.tzero_tr_error_min IS 'Time of passage at the center of the transit light curve for the primary transit error min';
COMMENT ON COLUMN fact_observation.tzero_tr_error_max IS 'Time of passage at the center of the transit light curve for the primary transit error max';
COMMENT ON COLUMN fact_observation.tzero_vr IS 'Time of zero, increasing, radial velocity (i.e. when the planet moves toward the observer) for circular orbits in Julian day';
COMMENT ON COLUMN fact_observation.tzero_vr_error_min IS 'Time of zero error min';
COMMENT ON COLUMN fact_observation.tzero_vr_error_max IS 'Time of zero error max';
COMMENT ON COLUMN fact_observation.t_peri IS 'Time of passage at the periapse for eccentric orbits in JD';
COMMENT ON COLUMN fact_observation.t_peri_error_min IS 'Time of passage at the periapse error min';
COMMENT ON COLUMN fact_observation.t_peri_error_max IS 'Time of passage at the periapse error max';
COMMENT ON COLUMN fact_observation.t_conj IS 'Time of the star-planet upper conjunction';
COMMENT ON COLUMN fact_observation.t_conj_error_min IS 'Time of the star-planet upper conjunction error min';
COMMENT ON COLUMN fact_observation.t_conj_error_max IS 'Time of the star-planet upper conjunction error max';
COMMENT ON COLUMN fact_observation.inclination IS 'Inclination of planet orbit, angle between the planet orbit and the sky plane';
COMMENT ON COLUMN fact_observation.inclination_error_min IS 'Inclination error min';
COMMENT ON COLUMN fact_observation.inclination_error_max IS 'Inclination error max';
COMMENT ON COLUMN fact_observation.tzero_tr_sec IS 'Time of passage at the center of the transit light curve for the secondary transit';
COMMENT ON COLUMN fact_observation.tzero_tr_sec_error_min IS 'Time of passage at the center of the transit light curve for the secondary transit error min';
COMMENT ON COLUMN fact_observation.tzero_tr_sec_error_max IS 'Time of passage at the center of the transit light curve for the secondary transit error max';
COMMENT ON COLUMN fact_observation.lambda_angle IS 'Sky-projected angle between the planetary orbital spin and the stellar rotational spin (Rossiter-McLaughlin anomaly)';
COMMENT ON COLUMN fact_observation.lambda_angle_error_min IS 'Sky-projected angle error min';
COMMENT ON COLUMN fact_observation.lambda_angle_error_max IS 'Sky-projected angle error max';
COMMENT ON COLUMN fact_observation.angular_distance IS 'Formal star-planet angular separation given by a/Distance';
COMMENT ON COLUMN fact_observation.temp_calculated IS 'Planet temperature as calculated by authors, based on a planet model';
COMMENT ON COLUMN fact_observation.temp_measured IS 'Planet temperature as measured by authors';
COMMENT ON COLUMN fact_observation.hot_point_lon IS 'Longitude of the planet hottest point';
COMMENT ON COLUMN fact_observation.log_g IS 'Surface gravity expressed in log of terrestrial g';
COMMENT ON COLUMN fact_observation.albedo IS 'Geometric albedo';
COMMENT ON COLUMN fact_observation.albedo_error_min IS 'Geometric albedo error min';
COMMENT ON COLUMN fact_observation.albedo_error_max IS 'Geometric albedo error max';
COMMENT ON COLUMN fact_observation.mass_sin_i IS 'Minimum mass of the planet due to inclination effect';
COMMENT ON COLUMN fact_observation.mass_sin_i_error_min IS 'Minimum mass error min of the planet due to inclination effect';
COMMENT ON COLUMN fact_observation.mass_sin_i_error_max IS 'Minimum mass error max of the planet due to inclination effect';
COMMENT ON COLUMN fact_observation.impact_parameter IS 'Minimum, in stellar radius units, of distance of the planet to the stellar center for transiting planets';
COMMENT ON COLUMN fact_observation.impact_parameter_error_min IS 'Impact Parameter error min';
COMMENT ON COLUMN fact_observation.impact_parameter_error_max IS 'Impact Parameter error max';
COMMENT ON COLUMN fact_observation.k IS 'Semi-amplitude of the radial velocity curve';
COMMENT ON COLUMN fact_observation.k_error_min IS 'Semi-amplitude error min';
COMMENT ON COLUMN fact_observation.k_error_max IS 'Semi-amplitude error max';
