COMMENT ON COLUMN raw_exoplanet_data.granule_uid IS 'Internal table row index, which must be unique within the table. Can be alphanumeric.';
COMMENT ON COLUMN raw_exoplanet_data.granule_gid IS 'Common to granules of same type (e.g. same map projection, or geometry data products). Can be alphanumeric.';
COMMENT ON COLUMN raw_exoplanet_data.obs_id IS 'Associates granules derived from the same data (e.g. various representations/processing levels). Can be alphanumeric, may be the ID of original observation.';
COMMENT ON COLUMN raw_exoplanet_data.dataproduct_type IS 'The high-level organization of the data product, from a controlled vocabulary (e.g., "im" for image, sp for spectrum). Multiple terms may be used, separated by # characters. [Note et_prod]';
COMMENT ON COLUMN raw_exoplanet_data.target_name IS 'Standard IAU name of target (from a list related to target class), case sensitive';
COMMENT ON COLUMN raw_exoplanet_data.target_class IS 'Type of target, from a controlled vocabulary.';
COMMENT ON COLUMN raw_exoplanet_data.time_min IS 'Acquisition start time (in JD), as UTC at time_refposition';
COMMENT ON COLUMN raw_exoplanet_data.time_max IS 'Acquisition stop time (in JD), as UTC at time_refposition';
COMMENT ON COLUMN raw_exoplanet_data.time_sampling_step_min IS 'Sampling time for measurements of dynamical phenomena, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.time_sampling_step_max IS 'Sampling time for measurements of dynamical phenomena, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.time_exp_min IS 'Integration time of the measurement, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.time_exp_max IS 'Integration time of the measurement, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.spectral_range_min IS 'Spectral range (frequency), lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.spectral_range_max IS 'Spectral range (frequency), upper limit';
COMMENT ON COLUMN raw_exoplanet_data.spectral_sampling_step_min IS 'Spectral sampling step, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.spectral_sampling_step_max IS 'Spectral sampling step, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.spectral_resolution_min IS 'Spectral resolution, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.spectral_resolution_max IS 'Spectral resolution, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.c1min IS 'Right Ascension (ICRS), lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.c1max IS 'Right Ascension (ICRS), upper limit';
COMMENT ON COLUMN raw_exoplanet_data.c2min IS 'Declination (ICRS), lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.c2max IS 'Declination (ICRS), upper limit';
COMMENT ON COLUMN raw_exoplanet_data.c3min IS 'Distance from coordinate origin, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.c3max IS 'Distance from coordinate origin, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.s_region IS 'ObsCore-like footprint, valid for celestial, spherical, or body-fixed frames';
COMMENT ON COLUMN raw_exoplanet_data.c1_resol_min IS 'Resolution in the first coordinate, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.c1_resol_max IS 'Resolution in the first coordinate, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.c2_resol_min IS 'Resolution in the second coordinate, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.c2_resol_max IS 'Resolution in the second coordinate, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.c3_resol_min IS 'Resolution in the third coordinate, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.c3_resol_max IS 'Resolution in the third coordinate, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.spatial_frame_type IS 'Flavor of coordinate system, defines the nature of coordinates. From a controlled vocabulary, where "none" means undefined.';
COMMENT ON COLUMN raw_exoplanet_data.incidence_min IS 'Incidence angle (solar zenithal angle) during data acquisition, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.incidence_max IS 'Incidence angle (solar zenithal angle) during data acquisition, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.emergence_min IS 'Emergence angle during data acquisition, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.emergence_max IS 'Emergence angle during data acquisition, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.phase_min IS 'Phase angle during data acquisition, lower limit.';
COMMENT ON COLUMN raw_exoplanet_data.phase_max IS 'Phase angle during data acquisition, upper limit';
COMMENT ON COLUMN raw_exoplanet_data.instrument_host_name IS 'Standard name of the observatory or spacecraft';
COMMENT ON COLUMN raw_exoplanet_data.instrument_name IS 'Standard name of instrument';
COMMENT ON COLUMN raw_exoplanet_data.measurement_type IS 'UCD(s) defining the data, with multiple entries separated by hash (#) characters.';
COMMENT ON COLUMN raw_exoplanet_data.processing_level IS 'Dataset-related encoding, or simplified CODMAC calibration level [Note et_cal]';
COMMENT ON COLUMN raw_exoplanet_data.creation_date IS 'Date of first entry of this granule';
COMMENT ON COLUMN raw_exoplanet_data.modification_date IS 'Date of last modification (used to handle mirroring)';
COMMENT ON COLUMN raw_exoplanet_data.release_date IS 'Start of public access period';
COMMENT ON COLUMN raw_exoplanet_data.service_title IS 'Title of resource (an acronym really, will be used to handle multiservice results)';
COMMENT ON COLUMN raw_exoplanet_data.time_scale IS 'Defaults to UTC in data services; takes values from http://www.ivoa.net/rdf/time_scale otherwise';
COMMENT ON COLUMN raw_exoplanet_data.publisher IS 'A short string identifying the entity running the data service used';
COMMENT ON COLUMN raw_exoplanet_data.bib_reference IS 'Bibcode or DOI preferred if available, or other bibliographic identifier or URL';
COMMENT ON COLUMN raw_exoplanet_data.target_region IS 'Region of interest';
COMMENT ON COLUMN raw_exoplanet_data.species IS 'Species detected in the planet';
COMMENT ON COLUMN raw_exoplanet_data.detection_type IS 'Methods of discovery/detection of the planet (RV, transit, TTV, lensing, astrometry, imaging). The first method is the discovery one';
COMMENT ON COLUMN raw_exoplanet_data.publication_status IS 'Publication status of exoplanet information';
COMMENT ON COLUMN raw_exoplanet_data.mass IS 'Mass of the planet';
COMMENT ON COLUMN raw_exoplanet_data.mass_error_min IS 'Mass error min';
COMMENT ON COLUMN raw_exoplanet_data.mass_error_max IS 'Mass error max';
COMMENT ON COLUMN raw_exoplanet_data.radius IS 'Radius of the planet';
COMMENT ON COLUMN raw_exoplanet_data.radius_error_min IS 'Radius error min';
COMMENT ON COLUMN raw_exoplanet_data.radius_error_max IS 'Radius error max';
COMMENT ON COLUMN raw_exoplanet_data.semi_major_axis IS 'Semi-major axis of the planet orbit';
COMMENT ON COLUMN raw_exoplanet_data.semi_major_axis_error_min IS 'Semi-major axis error min';
COMMENT ON COLUMN raw_exoplanet_data.semi_major_axis_error_max IS 'Semi-major axis error max';
COMMENT ON COLUMN raw_exoplanet_data.period IS 'Orbital period of the planet';
COMMENT ON COLUMN raw_exoplanet_data.period_error_min IS 'Orbital period error min';
COMMENT ON COLUMN raw_exoplanet_data.period_error_max IS 'Orbital period error max';
COMMENT ON COLUMN raw_exoplanet_data.eccentricity IS 'Eccentrity of the planet orbit from 0, circular orbit, to almost 1, very elongated orbit';
COMMENT ON COLUMN raw_exoplanet_data.eccentricity_error_min IS 'Eccentrity error min';
COMMENT ON COLUMN raw_exoplanet_data.eccentricity_error_max IS 'Eccentrity error max';
COMMENT ON COLUMN raw_exoplanet_data.periastron IS 'Periapse longitude : angle between the periapse and the line nodes in the orbit plane';
COMMENT ON COLUMN raw_exoplanet_data.periastron_error_min IS 'Periapse error min';
COMMENT ON COLUMN raw_exoplanet_data.periastron_error_max IS 'Periapse error max';
COMMENT ON COLUMN raw_exoplanet_data.tzero_tr IS 'Time of passage at the center of the transit light curve for the primary transit';
COMMENT ON COLUMN raw_exoplanet_data.tzero_tr_error_min IS 'Time of passage at the center of the transit light curve for the primary transit error min';
COMMENT ON COLUMN raw_exoplanet_data.tzero_tr_error_max IS 'Time of passage at the center of the transit light curve for the primary transit error max';
COMMENT ON COLUMN raw_exoplanet_data.tzero_vr IS 'Time of zero, increasing, radial velocity (i.e. when the planet moves toward the observer) for circular orbits in Julian day';
COMMENT ON COLUMN raw_exoplanet_data.tzero_vr_error_min IS 'Time of zero error min';
COMMENT ON COLUMN raw_exoplanet_data.tzero_vr_error_max IS 'Time of zero error max';
COMMENT ON COLUMN raw_exoplanet_data.t_peri IS 'Time of passage at the periapse for eccentric orbits in JD';
COMMENT ON COLUMN raw_exoplanet_data.t_peri_error_min IS 'Time of passage at the periapse error min';
COMMENT ON COLUMN raw_exoplanet_data.t_peri_error_max IS 'Time of passage at the periapse error max';
COMMENT ON COLUMN raw_exoplanet_data.t_conj IS 'Time of the star-planet upper conjunction';
COMMENT ON COLUMN raw_exoplanet_data.t_conj_error_min IS 'Time of the star-planet upper conjunction error min';
COMMENT ON COLUMN raw_exoplanet_data.t_conj_error_max IS 'Time of the star-planet upper conjunction error max';
COMMENT ON COLUMN raw_exoplanet_data.inclination IS 'Inclination of planet orbit, angle between the planet orbit and the sky plane';
COMMENT ON COLUMN raw_exoplanet_data.inclination_error_min IS 'Inclination error min';
COMMENT ON COLUMN raw_exoplanet_data.inclination_error_max IS 'Inclination error max';
COMMENT ON COLUMN raw_exoplanet_data.tzero_tr_sec IS 'Time of passage at the center of the transit light curve for the secondary transit';
COMMENT ON COLUMN raw_exoplanet_data.tzero_tr_sec_error_min IS 'Time of passage at the center of the transit light curve for the secondary transit error min';
COMMENT ON COLUMN raw_exoplanet_data.tzero_tr_sec_error_max IS 'Time of passage at the center of the transit light curve for the secondary transit error max';
COMMENT ON COLUMN raw_exoplanet_data.lambda_angle IS 'Sky-projected angle between the planetary orbital spin and the stellar rotational spin (Rossiter-McLaughlin anomaly)';
COMMENT ON COLUMN raw_exoplanet_data.lambda_angle_error_min IS 'Sky-projected angle error min';
COMMENT ON COLUMN raw_exoplanet_data.lambda_angle_error_max IS 'Sky-projected angle error max';
COMMENT ON COLUMN raw_exoplanet_data.discovered IS 'Year of discovery at the time of acceptance of a paper';
COMMENT ON COLUMN raw_exoplanet_data.updated IS 'Date of the last update of data';
COMMENT ON COLUMN raw_exoplanet_data.remarks IS 'remarks';
COMMENT ON COLUMN raw_exoplanet_data.other_web IS 'other web';
COMMENT ON COLUMN raw_exoplanet_data.angular_distance IS 'Formal star-planet angular separation given by a/Distance';
COMMENT ON COLUMN raw_exoplanet_data.temp_calculated IS 'Planet temperature as calculated by authors, based on a planet model';
COMMENT ON COLUMN raw_exoplanet_data.temp_measured IS 'Planet temperature as measured by authors';
COMMENT ON COLUMN raw_exoplanet_data.hot_point_lon IS 'Longitude of the planet hottest point';
COMMENT ON COLUMN raw_exoplanet_data.log_g IS 'Surface gravity expressed in log of terrestrial g';
COMMENT ON COLUMN raw_exoplanet_data.albedo IS 'Geometric albedo';
COMMENT ON COLUMN raw_exoplanet_data.albedo_error_min IS 'Geometric albedo error min';
COMMENT ON COLUMN raw_exoplanet_data.albedo_error_max IS 'Geometric albedo error max';
COMMENT ON COLUMN raw_exoplanet_data.mass_detection_type IS 'Method of measurement of the planet mass (RV, astrometry, planet model for direct imaging)';
COMMENT ON COLUMN raw_exoplanet_data.radius_detection_type IS 'Method of measurement of the planet radius (transit, planet model for direct imaging)';
COMMENT ON COLUMN raw_exoplanet_data.mass_sin_i IS 'Minimum mass of the planet due to inclination effect';
COMMENT ON COLUMN raw_exoplanet_data.mass_sin_i_error_min IS 'Minimum mass error min of the planet due to inclination effect';
COMMENT ON COLUMN raw_exoplanet_data.mass_sin_i_error_max IS 'Minimum mass error max of the planet due to inclination effect';
COMMENT ON COLUMN raw_exoplanet_data.impact_parameter IS 'Minimum, in stellar radius units, of distance of the planet to the stellar center for transiting planets';
COMMENT ON COLUMN raw_exoplanet_data.impact_parameter_error_min IS 'Impact Parameter error min';
COMMENT ON COLUMN raw_exoplanet_data.impact_parameter_error_max IS 'Impact Parameter error max';
COMMENT ON COLUMN raw_exoplanet_data.k IS 'Semi-amplitude of the radial velocity curve';
COMMENT ON COLUMN raw_exoplanet_data.k_error_min IS 'Semi-amplitude error min';
COMMENT ON COLUMN raw_exoplanet_data.k_error_max IS 'Semi-amplitude error max';
COMMENT ON COLUMN raw_exoplanet_data.alt_target_name IS 'Alternatives names of the planet';
COMMENT ON COLUMN raw_exoplanet_data.star_name IS 'Name of the host star';
COMMENT ON COLUMN raw_exoplanet_data.star_distance IS 'Distance of the star to the observer';
COMMENT ON COLUMN raw_exoplanet_data.star_distance_error_min IS 'Distance of the star error min';
COMMENT ON COLUMN raw_exoplanet_data.star_distance_error_max IS 'Distance of the star error max';
COMMENT ON COLUMN raw_exoplanet_data.star_spec_type IS 'Stellar spectral type';
COMMENT ON COLUMN raw_exoplanet_data.mag_v IS 'Apparent magnitude in the V band';
COMMENT ON COLUMN raw_exoplanet_data.mag_i IS 'Apparent magnitude in the I band';
COMMENT ON COLUMN raw_exoplanet_data.mag_j IS 'Apparent magnitude in the J band';
COMMENT ON COLUMN raw_exoplanet_data.mag_h IS 'Apparent magnitude in the H band';
COMMENT ON COLUMN raw_exoplanet_data.mag_k IS 'Apparent magnitude in the K band';
COMMENT ON COLUMN raw_exoplanet_data.star_metallicity IS 'Decimal logarithm of the massive elements (Â« metals Â») to hydrogen ratio in solar units (i.e. Log [(metals/H)star/(metals/H)Sun])';
COMMENT ON COLUMN raw_exoplanet_data.star_mass IS 'Star mass';
COMMENT ON COLUMN raw_exoplanet_data.star_radius IS 'Star radius';
COMMENT ON COLUMN raw_exoplanet_data.star_age IS 'Stellar age';
COMMENT ON COLUMN raw_exoplanet_data.star_teff IS 'Effective stellar temperature';
COMMENT ON COLUMN raw_exoplanet_data.magnetic_field IS 'Stellar magnetic field detected';
COMMENT ON COLUMN raw_exoplanet_data.detected_disc IS '(direct imaging or IR excess) disc detected';
COMMENT ON COLUMN raw_exoplanet_data.ra IS 'Right ascension of the host star';
COMMENT ON COLUMN raw_exoplanet_data.dec IS 'Declination of the host star';
COMMENT ON COLUMN raw_exoplanet_data.external_link IS 'Url of the planet page on exoplanet.eu';
