CREATE TABLE IF NOT EXISTS dim_star(
    star_key BIGSERIAL,
    star_name TEXT,
    star_distance DOUBLE PRECISION,
    star_distance_error_min DOUBLE PRECISION,
    star_distance_error_max DOUBLE PRECISION,
    star_spec_type TEXT,
    mag_v DOUBLE PRECISION,
    mag_i DOUBLE PRECISION,
    mag_j DOUBLE PRECISION,
    mag_h DOUBLE PRECISION,
    mag_k DOUBLE PRECISION,
    star_metallicity DOUBLE PRECISION,
    star_mass DOUBLE PRECISION,
    star_radius DOUBLE PRECISION,
    star_age DOUBLE PRECISION,
    star_teff DOUBLE PRECISION,
    magnetic_field BOOLEAN,
    detected_disc TEXT,
    ra DOUBLE PRECISION,
    dec DOUBLE PRECISION,
    external_link TEXT,
    modification_date TIMESTAMP,
    is_current BOOLEAN,
    current_as_of DATE,
    date_expired DATE,
    PRIMARY KEY(star_key)
);